[build]
builder = "NIXPACKS"
buildCommand = """
python -m pip install --upgrade pip
pip install -r requirements.txt
"""

[deploy]
startCommand = "python deploy.py && uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
PYTHON_VERSION = "3.9.18"
NIXPACKS_PYTHON_VERSION = "3.9.18"
