[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python -c \"import os; port = int(os.getenv('PORT', '8000')); from subprocess import run; run(['uvicorn', 'main:app', '--host', '0.0.0.0', '--port', str(port), '--log-level', 'debug'])\""
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
