"""Add gamification columns

Revision ID: bc4c25925ee4
Revises: 
Create Date: 2025-01-04 21:27:58.059424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc4c25925ee4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('total_points', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('level', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('experience_points', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('title', sa.String(), nullable=True))
    op.add_column('users', sa.Column('spotify_connected', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('social_handle', sa.String(), nullable=True))
    op.add_column('users', sa.Column('preferred_gym', sa.String(), nullable=True))
    op.add_column('users', sa.Column('workout_style', sa.String(), nullable=True))
    op.drop_index('ix_users_name', table_name='users')
    op.drop_index('ix_users_phone', table_name='users')
    op.add_column('workouts', sa.Column('completion_date', sa.DateTime(), nullable=True))
    op.add_column('workouts', sa.Column('difficulty_rating', sa.Integer(), nullable=True))
    op.add_column('workouts', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('workouts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('workouts', sa.Column('soundtrack_id', sa.String(), nullable=True))
    op.add_column('workouts', sa.Column('workout_intensity', sa.String(), nullable=True))
    op.alter_column('workouts', 'exercises',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('workouts', 'completed',
               existing_type=sa.VARCHAR(),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.drop_column('workouts', 'date')
    op.drop_column('workouts', 'feedback')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('feedback', sa.VARCHAR(), nullable=True))
    op.add_column('workouts', sa.Column('date', sa.DATETIME(), nullable=True))
    op.alter_column('workouts', 'completed',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('workouts', 'exercises',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('workouts', 'workout_intensity')
    op.drop_column('workouts', 'soundtrack_id')
    op.drop_column('workouts', 'created_at')
    op.drop_column('workouts', 'notes')
    op.drop_column('workouts', 'difficulty_rating')
    op.drop_column('workouts', 'completion_date')
    op.create_index('ix_users_phone', 'users', ['phone'], unique=1)
    op.create_index('ix_users_name', 'users', ['name'], unique=False)
    op.drop_column('users', 'workout_style')
    op.drop_column('users', 'preferred_gym')
    op.drop_column('users', 'social_handle')
    op.drop_column('users', 'spotify_connected')
    op.drop_column('users', 'title')
    op.drop_column('users', 'experience_points')
    op.drop_column('users', 'level')
    op.drop_column('users', 'total_points')
    # ### end Alembic commands ###
